
// Shape.h - DO NOT EDIT THIS FILE!

#pragma once

#include <string>

class Shape
{

public:

	// Non-virtual members

	Shape() { }
	virtual ~Shape() { }

	void Display();


	// Virtual members

	virtual std::string GetType() { return "Shape"; }

	virtual double GetArea() = 0;

	virtual double GetPerimeter() = 0;
};
