
// Shape.h - DO NOT EDIT THIS FILE!

#pragma once

#include <string>

class Shape
{

public:

	// Non-virtual members

	Shape() { }
	Shape(const Shape&) = delete;
	virtual ~Shape() { }

	Shape& operator=(const Shape&) = delete;

	void Display() const;


	// Virtual members

	virtual std::string GetType() const { return "Shape"; }

	virtual float GetArea() const = 0;

	virtual float GetPerimeter() const = 0;

};
