
// Triangle.cpp - DO NOT EDIT THIS FILE!

#include <math.h>

#include "Triangle.h"


Triangle::Triangle(const float sideA, const float sideB, const float sideC)
{
	SetSides(sideA, sideB, sideC);
}


void Triangle::SetSideA(const float size)
{ 
	if (size > 0) m_sideA = size;
	else m_sideA = 1;
}


void Triangle::SetSideB(const float size)
{
	if (size > 0) m_sideB = size;
	else m_sideB = 1;
}


void Triangle::SetSideC(const float size)
{
	if (size > 0) m_sideC = size;
	else m_sideC = 1;
}



void Triangle::SetSides(const float a, const float b, const float c)
{
	SetSideA(a);
	SetSideB(b);
	SetSideC(c);
}


float Triangle::GetArea() const
{
	float p = GetPerimeter() / 2;
	return (float)sqrt(p * (p - m_sideA) * (p - m_sideB) * (p - m_sideC));
}


float Triangle::GetPerimeter() const
{
	return m_sideA + m_sideB + m_sideC;
}