
// Circle.h - DO NOT EDIT THIS FILE!

#pragma once

#include "Shape.h"

class Triangle : public Shape
{
private:

	float m_sideA = 1;
	float m_sideB = 1;
	float m_sideC = 1;

public:

	Triangle() { }
	Triangle(const float sideA, const float sideB, const float sideC);

	virtual float GetSideA() const { return m_sideA; }
	virtual float GetSideB() const { return m_sideB; }
	virtual float GetSideC() const { return m_sideC; }

	// Mutators
	virtual void SetSideA(const float size);
	virtual void SetSideB(const float size);
	virtual void SetSideC(const float size);

	virtual void SetSides(const float a, const float b, const float c);

	virtual std::string GetType() { return "Triangle"; }

	virtual float GetArea() const;

	virtual float GetPerimeter() const;

};